package se.yrgo.dataaccess;

import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;

import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {

    private JdbcTemplate jdbcTemplate;

    public void createTables() {
        jdbcTemplate.execute("DROP TABLE CUSTOMER IF EXISTS");
        jdbcTemplate.execute("DROP TABLE CALLS IF EXISTS");

        jdbcTemplate.execute(
                "CREATE TABLE CUSTOMER (" +
                        "CUSTOMER_ID VARCHAR(10) PRIMARY KEY, " +
                        "NAME VARCHAR(100), " +
                        "NOTES VARCHAR(255))");

        jdbcTemplate.execute(
                "CREATE TABLE CALLS (" +
                        "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "CUSTOMER_ID VARCHAR(10), " +
                        "DESCRIPTION VARCHAR(255))");
    }

    public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void create(Customer customer) {
        jdbcTemplate.update(
                "INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, NOTES) VALUES (?, ?, ?)",
                customer.getCustomerId(),
                customer.getCompanyName(),
                customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        try {
            return jdbcTemplate.queryForObject(
                    "SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = ?",
                    (rs, rowNum) -> new Customer(
                            rs.getString("CUSTOMER_ID"),
                            rs.getString("NAME"),
                            rs.getString("NOTES")),
                    customerId);
        } catch (Exception e) {
            throw new RecordNotFoundException("Customer not found: " + customerId);
        }
    }

    @Override
    public List<Customer> getByName(String name) {
        return jdbcTemplate.query(
                "SELECT * FROM CUSTOMER WHERE LOWER(NAME) LIKE ?",
                (rs, rowNum) -> new Customer(
                        rs.getString("CUSTOMER_ID"),
                        rs.getString("NAME"),
                        rs.getString("NOTES")),
                "%" + name.toLowerCase() + "%");
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        int rows = jdbcTemplate.update(
                "UPDATE CUSTOMER SET NAME = ?, NOTES = ? WHERE CUSTOMER_ID = ?",
                customerToUpdate.getCompanyName(),
                customerToUpdate.getNotes(),
                customerToUpdate.getCustomerId());

        if (rows == 0) {
            throw new RecordNotFoundException("Customer not found");
        }
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        int rows = jdbcTemplate.update(
                "DELETE FROM CUSTOMER WHERE CUSTOMER_ID = ?",
                oldCustomer.getCustomerId());

        if (rows == 0) {
            throw new RecordNotFoundException("Customer not found");
        }
    }

    @Override
    public List<Customer> getAllCustomers() {
        return jdbcTemplate.query(
                "SELECT * FROM CUSTOMER",
                (rs, rowNum) -> new Customer(
                        rs.getString("CUSTOMER_ID"),
                        rs.getString("NAME"),
                        rs.getString("NOTES")));
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        Customer customer = getById(customerId);

        List<Call> calls = jdbcTemplate.query(
                "SELECT * FROM CALLS WHERE CUSTOMER_ID = ?",
                (rs, rowNum) -> new Call(rs.getString("DESCRIPTION")),
                customerId);

        customer.setCalls(calls);
        return customer;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        jdbcTemplate.update(
                "INSERT INTO CALLS (CUSTOMER_ID, DESCRIPTION) VALUES (?, ?)",
                customerId,
                newCall.getNotes());
    }
}
